/**
 * SmartHome.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("GarageApi", () => {
  let instance: api.GarageApi
  beforeEach(function() {
    instance = new api.GarageApi(config)
  });

  test("garageIdCyclicHeatTimesGet", () => {
    const id: number = 56
    return expect(instance.garageIdCyclicHeatTimesGet(id, {})).resolves.toBe(null)
  })
  test("garageIdCyclicHeatTimesSavePut", () => {
    const id: number = 56
    const body: api.CyclicHeatRequestsDto = undefined
    return expect(instance.garageIdCyclicHeatTimesSavePut(id, body, {})).resolves.toBe(null)
  })
  test("garageIdGaragesGet", () => {
    const id: number = 56
    return expect(instance.garageIdGaragesGet(id, {})).resolves.toBe(null)
  })
  test("garageIdHeatTimeRequestGet", () => {
    const id: number = 56
    return expect(instance.garageIdHeatTimeRequestGet(id, {})).resolves.toBe(null)
  })
  test("garageIdHeatTimeRequestSavePost", () => {
    const id: number = 56
    const body: api.HeatRequestDto = undefined
    return expect(instance.garageIdHeatTimeRequestSavePost(id, body, {})).resolves.toBe(null)
  })
  test("garageIdHeaterPatch", () => {
    const id: number = 56
    return expect(instance.garageIdHeaterPatch(id, {})).resolves.toBe(null)
  })
  test("garageIdTemperaturesGet", () => {
    const id: number = 56
    return expect(instance.garageIdTemperaturesGet(id, {})).resolves.toBe(null)
  })
})

