// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmartHomeDbContext))]
    [Migration("20240303115456_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.CyclicHeatTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("GarageId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("interval");

                    b.HasKey("Id")
                        .HasName("CyclicHeatTask_pkey");

                    b.HasIndex(new[] { "GarageId" }, "IX_CyclicHeatTask_GarageId");

                    b.ToTable("CyclicHeatTask", "Garages");
                });

            modelBuilder.Entity("Core.Entities.CyclicHeatTaskDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CyclicHeatTaskId")
                        .HasColumnType("integer");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("CyclicHeatTaskDaysInWeek_pkey");

                    b.HasIndex(new[] { "CyclicHeatTaskId" }, "IX_CyclicHeatTaskDaysInWeek_CyclicHeatTaskId");

                    b.HasIndex(new[] { "Day" }, "IX_CyclicHeatTaskDaysInWeek_DayId");

                    b.ToTable("CyclicHeatTaskDay", "Garages");
                });

            modelBuilder.Entity("Core.Entities.Garage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("Garage_pkey");

                    b.ToTable("Garage", "Garages");
                });

            modelBuilder.Entity("Core.Entities.HeatLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Info")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("HeatLog_pkey");

                    b.ToTable("HeatLog", "Garages");
                });

            modelBuilder.Entity("Core.Entities.HeatTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GarageId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("HeatTask_pkey");

                    b.HasIndex(new[] { "GarageId" }, "IX_HeatTask_GarageId");

                    b.ToTable("HeatTask", "Garages");
                });

            modelBuilder.Entity("Core.Entities.OutsideTemperature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GarageId")
                        .HasColumnType("integer");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.HasKey("Id")
                        .HasName("OutsideTemperature_pkey");

                    b.HasIndex(new[] { "GarageId" }, "IX_OutsideTemperature_GarageId");

                    b.ToTable("OutsideTemperature", "Garages");
                });

            modelBuilder.Entity("Core.Entities.CyclicHeatTask", b =>
                {
                    b.HasOne("Core.Entities.Garage", "Garage")
                        .WithMany("CyclicHeatTasks")
                        .HasForeignKey("GarageId")
                        .IsRequired()
                        .HasConstraintName("GarageId");

                    b.Navigation("Garage");
                });

            modelBuilder.Entity("Core.Entities.CyclicHeatTaskDay", b =>
                {
                    b.HasOne("Core.Entities.CyclicHeatTask", "CyclicHeatTask")
                        .WithMany("CyclicHeatTaskDays")
                        .HasForeignKey("CyclicHeatTaskId")
                        .IsRequired()
                        .HasConstraintName("CyclicHeatTaskId");

                    b.Navigation("CyclicHeatTask");
                });

            modelBuilder.Entity("Core.Entities.HeatTask", b =>
                {
                    b.HasOne("Core.Entities.Garage", "Garage")
                        .WithMany("HeatTasks")
                        .HasForeignKey("GarageId")
                        .IsRequired()
                        .HasConstraintName("GarageId");

                    b.Navigation("Garage");
                });

            modelBuilder.Entity("Core.Entities.OutsideTemperature", b =>
                {
                    b.HasOne("Core.Entities.Garage", "Garage")
                        .WithMany("OutsideTemperatures")
                        .HasForeignKey("GarageId")
                        .IsRequired()
                        .HasConstraintName("GarageId");

                    b.Navigation("Garage");
                });

            modelBuilder.Entity("Core.Entities.CyclicHeatTask", b =>
                {
                    b.Navigation("CyclicHeatTaskDays");
                });

            modelBuilder.Entity("Core.Entities.Garage", b =>
                {
                    b.Navigation("CyclicHeatTasks");

                    b.Navigation("HeatTasks");

                    b.Navigation("OutsideTemperatures");
                });
#pragma warning restore 612, 618
        }
    }
}
