FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
USER $APP_UID
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Directory.Packages.props", "."]
COPY ["src/SmartHome.Worker/*.csproj", "src/SmartHome.Worker/"]
COPY ["src/Core/*.csproj", "src/Core/"]
COPY ["src/Infrastructure/*.csproj", "src/Infrastructure/"]
RUN dotnet restore "src/SmartHome.Worker/SmartHome.Worker.csproj" -r linux-x64
COPY . .
WORKDIR "/src/src/SmartHome.Worker"
RUN dotnet build "SmartHome.Worker.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "SmartHome.Worker.csproj" -c Release -o /app/publish  -r linux-x64 /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SmartHome.Worker.dll"]
