# https://stackoverflow.com/a/78110854/24537942

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base

USER $APP_UID
WORKDIR /app

EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-net

WORKDIR /src

# copy required project files
COPY ["Directory.Packages.props", "."]
COPY ["src/SmartHome.ClientApp/SmartHome.ClientApp.csproj", "src/SmartHome.ClientApp/"]

# and restore dependencies
RUN dotnet restore "src/SmartHome.ClientApp/SmartHome.ClientApp.csproj" -r linux-x64

COPY . .

# build the project
WORKDIR "src/SmartHome.ClientApp"
RUN dotnet build -c Release -o /app/build -r linux-x64

# publish the project
FROM build-net AS publish

ARG BACKEND_APP_VERSION=1.0.0
ARG BACKEND_APP_VERSION_SUFFIX=

RUN dotnet publish \
    -c Release \
    -o /app/publish \
    -r linux-x64 \
    /p:UseAppHost=false \
    /p:SpaRunPublishVite=false \
    /p:VersionPrefix=${BACKEND_APP_VERSION} \
    /p:VersionSuffix=${BACKEND_APP_VERSION_SUFFIX}

FROM node:20-alpine as build-node

WORKDIR /ClientApp

COPY ["src/SmartHome.ClientApp/ClientApp/package.json", "."]
COPY ["src/SmartHome.ClientApp/ClientApp/package-lock.json", "."]

RUN npm ci

COPY ["src/SmartHome.ClientApp/ClientApp/", "."]

ARG FRONTEND_APP_VERSION=vNext

RUN printf "VITE_APP_NAME=SmartHome\n" >> .env.production.local && \
    printf "VITE_APP_VERSION=${FRONTEND_APP_VERSION}\n" >> .env.production.local

# npm run build (vite build) will load the .env.production.local file
RUN npm run build

FROM base AS final

# make sure that the Polish timezone is set in system
USER root
ENV TZ=Europe/Warsaw
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
USER $APP_UID

# create final image
WORKDIR /app
COPY --from=publish /app/publish .
COPY --from=build-node /ClientApp/dist ./wwwroot

# run the application
ENTRYPOINT ["dotnet", "SmartHome.Client.dll"]
