FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080


FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Directory.Packages.props", "."]
COPY ["src/SmartHome.Api/SmartHome.Api.csproj", "src/SmartHome.Api/"]
COPY ["src/Core/Core.csproj", "src/Core/"]
COPY ["src/Infrastructure/Infrastructure.csproj", "src/Infrastructure/"]
RUN dotnet restore "src/SmartHome.Api/SmartHome.Api.csproj" -r linux-x64
COPY . .
WORKDIR "/src/src/SmartHome.Api"
RUN dotnet build "SmartHome.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SmartHome.Api.csproj" -c Release -o /app/publish  -r linux-x64 /p:UseAppHost=false --self-contained false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SmartHome.Api.dll"]
