/* tslint:disable */
/* eslint-disable */
/**
 * SmartHome.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Garage } from './garage';
import { TimeSpan } from './time-span';
/**
 * 
 * @export
 * @interface CyclicHeatRequest
 */
export interface CyclicHeatRequest {
    /**
     * 
     * @type {number}
     * @memberof CyclicHeatRequest
     */
    garageId?: number;
    /**
     * 
     * @type {TimeSpan}
     * @memberof CyclicHeatRequest
     */
    monday?: TimeSpan;
    /**
     * 
     * @type {TimeSpan}
     * @memberof CyclicHeatRequest
     */
    tuesday?: TimeSpan;
    /**
     * 
     * @type {TimeSpan}
     * @memberof CyclicHeatRequest
     */
    wednesday?: TimeSpan;
    /**
     * 
     * @type {TimeSpan}
     * @memberof CyclicHeatRequest
     */
    thursday?: TimeSpan;
    /**
     * 
     * @type {TimeSpan}
     * @memberof CyclicHeatRequest
     */
    friday?: TimeSpan;
    /**
     * 
     * @type {TimeSpan}
     * @memberof CyclicHeatRequest
     */
    saturday?: TimeSpan;
    /**
     * 
     * @type {TimeSpan}
     * @memberof CyclicHeatRequest
     */
    sunday?: TimeSpan;
    /**
     * 
     * @type {Garage}
     * @memberof CyclicHeatRequest
     */
    garage?: Garage;
    /**
     * 
     * @type {number}
     * @memberof CyclicHeatRequest
     */
    id?: number;
}
