/* tslint:disable */
/* eslint-disable */
/**
 * SmartHome.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CyclicHeatRequests } from './cyclic-heat-requests';
/**
 * 
 * @export
 * @interface CyclicHeatRequestsDto
 */
export interface CyclicHeatRequestsDto {
    /**
     * 
     * @type {CyclicHeatRequests}
     * @memberof CyclicHeatRequestsDto
     */
    requests?: CyclicHeatRequests;
}
