/* tslint:disable */
/* eslint-disable */
/**
 * SmartHome.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CyclicHeatRequest } from './cyclic-heat-request';
import { HeatRequest } from './heat-request';
import { OutsideTemperature } from './outside-temperature';
/**
 * 
 * @export
 * @interface Garage
 */
export interface Garage {
    /**
     * 
     * @type {string}
     * @memberof Garage
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Garage
     */
    ip?: string | null;
    /**
     * 
     * @type {Array<CyclicHeatRequest>}
     * @memberof Garage
     */
    cyclicHeatRequests?: Array<CyclicHeatRequest> | null;
    /**
     * 
     * @type {Array<HeatRequest>}
     * @memberof Garage
     */
    heatRequests?: Array<HeatRequest> | null;
    /**
     * 
     * @type {Array<OutsideTemperature>}
     * @memberof Garage
     */
    outsideTemperatures?: Array<OutsideTemperature> | null;
    /**
     * 
     * @type {number}
     * @memberof Garage
     */
    id?: number;
}
