/* tslint:disable */
/* eslint-disable */
/**
 * SmartHome.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Garage } from './garage';
/**
 * 
 * @export
 * @interface OutsideTemperature
 */
export interface OutsideTemperature {
    /**
     * 
     * @type {Date}
     * @memberof OutsideTemperature
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof OutsideTemperature
     */
    temperature?: number;
    /**
     * 
     * @type {number}
     * @memberof OutsideTemperature
     */
    garageId?: number;
    /**
     * 
     * @type {Garage}
     * @memberof OutsideTemperature
     */
    garage?: Garage;
    /**
     * 
     * @type {number}
     * @memberof OutsideTemperature
     */
    id?: number;
}
