name: Trigger auto deployment for tet321

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ develop ]
    paths:
    - '**'
    - '.github/workflows/tet321-AutoDeployTrigger-b4cbb72c-f588-4ca0-9fd9-8b0b3719ce66.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TET321_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TET321_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TET321_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.TET321_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TET321_REGISTRY_PASSWORD }}
          containerAppName: tet321
          resourceGroup: smarthome
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


